version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '9:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '9:00'
      timezone: 'Europe/Madrid'
