version: '3'

services:
    shlink_webstie_node:
        container_name: shlink_webstie_node
        image: node:18.16-alpine
        command: /bin/sh -c "cd /shlink-website && npm install -f && npm run dev"
        volumes:
            - ./:/shlink-website
        ports:
            - "3000:3000"
