services:
    shlink_webstie_node:
        container_name: shlink_webstie_node
        user: 1000:1000
        build:
            context: .
            dockerfile: ./dev.Dockerfile
        working_dir: /shlink-website
        command: /bin/sh -c "npm install && node --run dev"
        volumes:
            - ./:/shlink-website
        ports:
            - "4321:4321"
            - "4322:4322"
