name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  ci:
    uses: shlinkio/github-actions/.github/workflows/web-app-ci.yml@main
    with:
      node-version: 22.x
      with-unit-tests: false
