name: Build docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    uses: shlinkio/github-actions/.github/workflows/docker-build-and-publish.yml@main
    secrets: inherit
    with:
      image-name: shlinkio/shlink.io
      platforms: linux/amd64
