name: Build docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    uses: shlinkio/github-actions/.github/workflows/docker-publish-image.yml@main
    secrets: inherit
    with:
      image-name: shlinkio/shlink-website
      platforms: linux/amd64
